k: 20  # target number of clusters for CSS stage
u: 5   # minimum factor count required before CoE expansion
css:
  n_select: 10
  similarity_metric: "spearman"
coe:
  max_depth: 5
  min_rankic: 0.05
  prompt_chains: 5
  # benchmark_assets: ["000852.SH", "000905.SH"]
  benchmark_assets: ["000852.SH"]
  prompt_expr_chars: 0
  ric_start_date: "2015-01-01"
  ric_end_date: "2020-12-31"
run:
  use_css: true
  use_coe: true
paths:
  market_data: "./data/fof_price_updating.parquet"
  factor_cache: "/Users/hpy/PycharmProjects/FAMA/data/factor_cache_new/factors.yaml"
  llm_factor_cache: "/Users/hpy/PycharmProjects/FAMA/data/factor_cache_new/LLM_factors.yaml"
  factor_outputs: "./data/factor_values"
  prompts_dir: "./prompts"
  output_dir: "./artifacts"
  factor_ric: "./factor_value_prepared/data/factors/factor_ric.csv"
llm:
#  provider: "openai"
#  model: "gpt-5"
#  api_key_env: "OPENAI_API_KEY"
  provider: "siliconflow"
  model: "Pro/deepseek-ai/DeepSeek-V3.2"
  base_url: "https://api.siliconflow.cn/v1"
  api_key_env: "SiliconFlow_API_KEY"
  temperature: 1
  thinking: "high"
  max_new_factors: 15
  instructions_path: "./prompts/alpha_prompt_template.txt"


  operator_whitelist:
    [
      "RANK",
      "DELTA",
      "DELAY",
      "TS_MEAN",
      "TS_SUM",
      "TS_STDDEV",
      "TS_MIN",
      "TS_MAX",
      "TS_PRODUCT",
      "TS_ARGMAX",
      "TS_ARGMIN",
      "TS_RANK",
      "CORREL",
      "COVAR",
      "SIGN",
      "ABS",
      "DECAY_LINEAR",
      "SCALE",
      "IF",
      "AND",
      "OR",
      "NOT",
      "GT",
      "GE",
      "LT",
      "LE",
      "EQ",
      "MAX",
      "MIN",
      "LOG",
      "EXP",
      "POW",
      "REPLACE_NAN_INF",
      "ADV",
      "SAFE_DIV",
      "CLIP",
      "EMA",
      "EXP_MOVING_AVG",
      "FAST_TS_SUM",
      "TS_QUANTILE",
      "TS_KURT",
      "TS_SKEW",
      "TS_MAXDRAWDOWN",
      "TS_LINEAR_REGRESSION_R2",
      "TS_LINEAR_REGRESSION_SLOPE",
      "TS_LINEAR_REGRESSION_RESI",
      "DIFF_WITH_WEIGHTED_SUM",
    ]
  deny_fields: []
logging:
  level: "INFO"
  log_file: "./logs/fama.log"
compute:
  use_kunquant: true
  threads: 4
  layout: "TS"
